#!/bin/bash
# phases/06-bootloader.sh - Limine bootloader installation (runs in chroot)
# Part of omarchy fork installer
# Replaces systemd-boot with Limine for BTRFS snapshot support

ui_section "Bootloader Installation (chroot)"

# Get partition info (passed as env vars from outside chroot)
if [[ -z "$BTRFS_PARTITION" ]]; then
    error "BTRFS_PARTITION not set - cannot configure bootloader"
    exit 1
fi

# Get EFI partition
EFI_PARTITION=$(findmnt -n -o SOURCE /boot)
if [[ -z "$EFI_PARTITION" ]]; then
    error "Could not detect EFI partition mounted at /boot"
    exit 1
fi

info "Installing Limine bootloader..."
info "EFI partition: $EFI_PARTITION"
info "BTRFS partition: $BTRFS_PARTITION"

# Install Limine to the ESP
info "Installing Limine to ESP..."
limine bios-install "$EFI_PARTITION"

# Create EFI directory structure
mkdir -p /boot/EFI/BOOT

# Copy Limine EFI file
info "Copying Limine EFI bootloader..."
cp /usr/share/limine/BOOTX64.EFI /boot/EFI/BOOT/

# Handle LUKS encryption
CRYPTDEVICE_PARAM=""
ROOT_PARAM=""

if [[ "$ENABLE_ENCRYPTION" == "true" ]]; then
    info "Configuring bootloader for LUKS encryption..."

    # Get LUKS partition UUID (the raw encrypted partition)
    if [[ -z "$LUKS_PARTITION" ]]; then
        error "LUKS_PARTITION not set - cannot configure encrypted bootloader"
        exit 1
    fi

    LUKS_UUID=$(blkid -s UUID -o value "$LUKS_PARTITION")

    if [[ -z "$LUKS_UUID" ]]; then
        warn "Could not get LUKS UUID, using device path"
        CRYPTDEVICE_PARAM="cryptdevice=${LUKS_PARTITION}:cryptroot"
    else
        CRYPTDEVICE_PARAM="cryptdevice=UUID=${LUKS_UUID}:cryptroot"
    fi

    # Root is the unlocked mapper device
    ROOT_PARAM="root=/dev/mapper/cryptroot"

    info "LUKS cryptdevice: $CRYPTDEVICE_PARAM"
else
    # No encryption - use PARTUUID if available
    PARTUUID=$(blkid -s PARTUUID -o value "$BTRFS_PARTITION")

    if [[ -z "$PARTUUID" ]]; then
        warn "Could not get PARTUUID, using device path"
        ROOT_PARAM="root=${BTRFS_PARTITION}"
    else
        ROOT_PARAM="root=PARTUUID=${PARTUUID}"
    fi
fi

# Build kernel parameters
if [[ -n "$CRYPTDEVICE_PARAM" ]]; then
    KERNEL_PARAMS="${CRYPTDEVICE_PARAM} ${ROOT_PARAM} rootflags=subvol=@ rw"
else
    KERNEL_PARAMS="${ROOT_PARAM} rootflags=subvol=@ rw"
fi

# Add NVIDIA parameters if needed
if [[ "$HAS_NVIDIA" == "true" ]]; then
    KERNEL_PARAMS="${KERNEL_PARAMS} nvidia_drm.modeset=1"
    info "Added NVIDIA kernel parameters"
fi

# Create Limine configuration
info "Creating Limine configuration..."
cat > /boot/limine.conf <<EOF
# Limine bootloader configuration
# Generated by arch installer

timeout: 5
default_entry: 1
interface_branding: Arch Linux
interface_branding_color: 2
hash_mismatch_panic: no

# Terminal colors (Tokyo Night palette)
term_background: 1a1b26
backdrop: 1a1b26
term_palette: 15161e;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;a9b1d6
term_palette_bright: 414868;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;c0caf5
term_foreground: c0caf5
term_foreground_bright: c0caf5
term_background_bright: 24283b

# Main boot entry
:Arch Linux
protocol: linux
kernel_path: boot():/vmlinuz-linux
EOF

# Add microcode if available
if [[ -n "$MICROCODE" ]]; then
    echo "module_path: boot():/${MICROCODE}.img" >> /boot/limine.conf
    info "Added microcode: $MICROCODE"
fi

# Add main initramfs and kernel parameters
cat >> /boot/limine.conf <<EOF
module_path: boot():/initramfs-linux.img
cmdline: ${KERNEL_PARAMS}

# Fallback boot entry
:Arch Linux (Fallback)
protocol: linux
kernel_path: boot():/vmlinuz-linux
EOF

# Add microcode to fallback
if [[ -n "$MICROCODE" ]]; then
    echo "module_path: boot():/${MICROCODE}.img" >> /boot/limine.conf
fi

# Add fallback initramfs
cat >> /boot/limine.conf <<EOF
module_path: boot():/initramfs-linux-fallback.img
cmdline: ${KERNEL_PARAMS}
EOF

# Show configuration
info "Limine configuration created:"
cat /boot/limine.conf
echo ""

success "Limine bootloader installed successfully"
success "Snapshot boot entries will be added by limine-snapper-sync after installation"
